# Конфигурационный файл для LCD-сервиса
[lcd]
# Пины GPIO для подключения LCD1602
pin_rs = 25
pin_en = 24
pins_data = [23, 17, 18, 22]

# Размеры дисплея
cols = 16
rows = 2

[temp_monitor]
# Интервал проверки температуры (в секундах)
interval = 5

[uptime_monitor]
# Интервал проверки аптайма (в секундах)
interval = 10

[ros_publisher]
# Тема для публикации температуры
temp_topic = "lcd_temperature"
# Тема для публикации аптайма
uptime_topic = "lcd_uptime"