apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: spot-system

resources:
  - deployment.yaml
  - i2c-bootstrap.yaml
  - lcd.yaml
  - performance-setup.yaml

configMapGenerator:
  - name: spot-node-label-config
    files:
      - node_label_config.py
      - servo_driver.py
      - spot_cli.py
      - lcd1602.py
      - champ_bridge.py
      - spotmicroai.urdf.xacro
      - joints_ros2.yaml
      - links_ros2.yaml
      - gait_ros2.yaml
      - base_to_footprint.yaml
      - footprint_to_odom.yaml
