apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: spot-system

resources:
  - deployment.yaml

configMapGenerator:
  - name: spot-node-label-config
    files:
      - node_label_config.py
      - servo_driver.py
      - spot_cli.py
      - champ_bridge.py
      - spotmicroai.urdf.xacro=champ/spotmicroai.urdf.xacro
      - joints_ros2.yaml=champ/joints_ros2.yaml
      - links_ros2.yaml=champ/links_ros2.yaml
      - gait_ros2.yaml=champ/gait_ros2.yaml
